# Load dependencies - add modules here if you need them
name: jupyter-env
dependencies:
  - python=3.11
  # Maths related
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  # Molecular modelling
  - ase
  - gpaw
  # Necessary for online atom viewing
  - nglview
  - ipywidgets
