# Load dependencies - add modules here if you need them
dependencies:
  - python
# Maths related
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
# Molecular modelling
  - ase
  - gpaw

# Necessary for online atom viewing
  - nglview
  - ipywidgets